---
:project: katello
:github_org: katello
:prior_releases:
  :3.9.1:
    :redmine_version_id: 919
:releases:
  :3.10.1:
    :redmine_version_id: 975
  :3.10.0:
    :redmine_version_id: 937
:code_name: Belgian Tripel
:repos:
  :katello:
    :main: true
    :branch: KATELLO-3.10
    :repo: https://github.com/Katello/katello.git
    :version_branch: true
  :katello-installer:
    :branch: KATELLO-3.10
    :repo: https://github.com/Katello/katello-installer.git
    :version_branch: true
  :foreman-packaging:
    :branch: rpm/1.20
    :repo: https://github.com/theforeman/foreman-packaging.git
  :hammer-cli-katello:
    :branch: 0.16.1
    :repo: https://github.com/Katello/hammer-cli-katello.git
  :katello-host-tools:
    :branch: 3.4.2
    :repo: https://github.com/Katello/katello-host-tools.git
  :bastion:
    :branch: 6.1.12
    :repo: https://github.com/Katello/bastion.git
  :puppet-candlepin:
    :branch: 5.2.1
    :repo: https://github.com/theforeman/puppet-candlepin
  :puppet-certs:
    :branch: 4.4-stable
    :repo: https://github.com/theforeman/puppet-certs
  :puppet-foreman_proxy_content:
    :branch: 7.3.2
    :repo: https://github.com/theforeman/puppet-foreman_proxy_content
  :puppet-katello:
    :branch: 8.2.0
    :repo: https://github.com/theforeman/puppet-katello
  :puppet-pulp:
    :branch: 5.7.0
    :repo: https://github.com/theforeman/puppet-pulp
  :puppet-qpid:
    :branch: 4.3.0
    :repo: https://github.com/theforeman/puppet-qpid
:ignores:
  - 24889 # closed, no PR
  - 24732 # closed, no PR
  - 25240 # fixed by another issue
  - 25561 # closed, no PR
  - 25545 # closed, no PR
  - 24432 # closed, no PR
  - 25571 # closed, no PR
  - 24400 # tracker
  - 25527 # docs, closed
  - 25632 # dup
  - 25573 # closed, no repro
  - 23512 # closed by others
  - 25830 # dup

:strict_keys: true
:gpg_key: '88287C2B'
:mash_scripts:
 - katello-3.10-thirdparty-candlepin-rhel7
 - katello-3.10-rhel7
:tags:
  - name: katello-3.10-thirdparty-candlepin-rhel7
    based_off: katello-thirdparty-candlepin-rhel7
    arches:
      - x86_64
  - name: katello-3.10-rhel7
    based_off: katello-nightly-rhel7
    helper_tags:
      katello-3.10-thirdparty-rhel7: katello-thirdparty-rhel7
      katello-3.10-rhel7-override: null
    build_target: katello-3.10-rhel7-build
    build_package_group_source_tag: katello-nightly-rhel7-build
    arches:
      - x86_64
    inherits:
      katello-3.10-rhel7-build:
        katello-3.10-rhel7-override: 0
        foreman-rails-1.20-rhel7: 2
        foreman-plugins-1.20-rhel7-override: 3
        foreman-1.20-nonscl-rhel7: 4
        foreman-1.20-rhel7: 10
      katello-3.10-rhel7-override:
        katello-3.10-rhel7: 0
      katello-3.10-rhel7:
        katello-3.10-thirdparty-rhel7: 0
    external_repos:
      - epel7
      - centos-sclo-rh-rhel-7
      - centos-7-server-updates
      - centos-7-server
