---
:project: katello
:github_org: katello
:nightly: true
:mash_scripts:
  - katello-pulpcore-nightly-el7
:tags:
  - name: katello-thirdparty-candlepin-rhel7
    based_off: null
    arches:
      - x86_64
  - name: katello-nightly-rhel7
    based_off: null
    helper_tags:
      katello-thirdparty-rhel7: null
      katello-nightly-rhel7-override: null
    build_target: katello-nightly-rhel7-build
    build_package_group_source_tag: katello-nightly-rhel7-build
    arches:
      - x86_64
    inherits:
      katello-nightly-rhel7-build:
        katello-nightly-rhel7-override: 0
        tfm-ror52-rhel7: 2
        foreman-plugins-nightly-rhel7: 3
        foreman-plugins-nightly-nonscl-rhel7: 4
        foreman-nightly-rhel7: 5
        foreman-nightly-nonscl-rhel7: 6
      katello-nightly-rhel7-override:
        katello-nightly-rhel7: 0
      katello-nightly-rhel7:
        katello-thirdparty-rhel7: 0
    external_repos:
      - epel-7
      - centos-sclo-rh-rhel-7
      - centos-7-server-updates
      - centos-7-server
  - name: katello-pulpcore-nightly-el7
    based_off: null
    arches:
      - x86_64
    build_target: katello-pulpcore-nightly-el7-build
    external_repos:
      - centos7-os
      - centos7-updates
    build_groups:
      build:
        - bash
        - bzip2
        - coreutils
        - cpio
        - diffutils
        - findutils
        - gawk
        - gcc
        - gcc-c++
        - grep
        - gzip
        - info
        - make
        - patch
        - python3-rpm-macros
        - redhat-release
        - redhat-rpm-config
        - rpm-build
        - sed
        - shadow-utils
        - tar
        - unzip
        - util-linux
        - which
        - xz
      srpm-build:
        - bash
        - python3-rpm-macros
        - redhat-release
        - redhat-rpm-config
        - rhpkg-simple
        - rpm-build
        - shadow-utils
