---
:project: pulp3
:github_org: pulp
:nightly: true
:tags:
  - name: pulp3-nightly-rhel7
    based_off: null
    helper_tags:
      pulp3-nightly-rhel7-override: null
    build_target: pulp3-nightly-rhel7-build
    build_package_group_source_tag: pulp3-nightly-rhel7-build
    arches:
      - x86_64
    inherits:
      pulp3-nightly-rhel7-build:
        pulp3-nightly-rhel7-override: 0
        pulp3-nightly-nonscl-rhel7: 10
      pulp3-nightly-rhel7-override:
        pulp3-nightly-rhel7: 0
    external_repos:
      - epel-7
      - centos-sclo-rh-rhel-7
      - centos-sclo-sclo-rhel-7
      - centos-7-server
      - rhel-7.0-server
  - name: pulp3-nightly-nonscl-rhel7
    based_off: null
    helper_tags:
      pulp3-nightly-rhel7-override: null
    build_target: pulp3-nightly-nonscl-rhel7-build
    build_package_group_source_tag: pulp3-nightly-nonscl-rhel7-build
    arches:
      - x86_64
    inherits:
      pulp3-nightly-nonscl-rhel7-build:
        pulp3-nightly-nonscl-rhel7-override: 0
      pulp3-nightly-nonscl-rhel7-override:
        pulp3-nightly-nonscl-rhel7: 0
    external_repos:
      - epel-7
      - centos-7-server
      - rhel-7.0-server
