---
:project: pulp
:github_org: pulp
:nightly: true
:tags:
  - name: pulp-nightly-rhel7
    build_target: pulp-nightly-rhel7-build
    build_package_group_source_tag: pulp-nightly-rhel7-build
    arches:
      - x86_64
    external_repos:
      - rhel-7.0-server
      - rhel-7.0-server-optional
      - epel-7
  - name: pulp-nightly-rhel6
    build_target: pulp-nightly-rhel6-build
    build_package_group_source_tag: pulp-nightly-rhel6-build
    arches:
      - x86_64
    external_repos:
      - epel-6
      - qpid-copr
      - rhel-6.6-server
      - rhel-6.6-server-optional
  - name: pulp-nightly-rhel5
    build_target: pulp-nightly-rhel5-build
    build_package_group_source_tag: pulp-nightly-rhel5-build
    arches:
      - x86_64
    external_repos:
      - rhel-5.9-server
      - epel-5
  - name: pulp-nightly-fedora27
    build_target: pulp-nightly-fedora27-build
    build_package_group_source_tag: pulp-nightly-fedora27-build
    arches:
      - x86_64
    external_repos:
      - fedora27-external-repo
      - fedora27-updates-external-repo
  - name: pulp-nightly-fedora26
    build_target: pulp-nightly-fedora26-build
    build_package_group_source_tag: pulp-nightly-fedora26-build
    arches:
      - x86_64
    external_repos:
      - fedora-26
      - fedora-26-updates
